version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB : wastehub
    networks:
      - wastehub
networks:
  wastehub: