version: '3.8'
services:
  dev-db:
    image: postgres:17
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - combatin

  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@dev-db:5432/${DB_NAME}
    depends_on:
      - dev-db
    networks:
      - combatin

networks:
  combatin:
    driver: bridge
